<?php
declare(strict_types=1);

namespace App\Controllers;

abstract class Authenticated extends \Core\Controller
{
	protected function before(): bool
	{
		$this->requireLogin();
		return parent::before(); // TODO: Change the autogenerated stub
	}
}