<?php
declare(strict_types=1);

namespace App\Controllers;


use App\Auth;
use App\Config;
use App\Flash;
use Core\View;

class Profile extends Authenticated
{


    protected function before(): bool
    {
        $this->user = Auth::getUser();
        return parent::before(); // TODO: Change the autogenerated stub
    }

    public function showAction(): void
    {
        View::renderTemplate('Profile/show.html.twig', [
            'user' => $this->user
        ]);
    }

    public function editAction(): void
    {
        View::renderTemplate('Profile/edit.html.twig', [
            'user' => $this->user
        ]);
    }

    public function updateAction(): void
    {

        if ($this->user->updateProfile($_POST)){

            Flash::addMessage('Changes saved!');

            $this->redirect('/'.Config::APP_NAME.'/profile/show');

        } else {

            Flash::addMessage('Something went wrong...', Flash::WARNING);

            View::renderTemplate('Profile/edit.html.twig', [
                'user' => $this->user
            ]);

        }
    }
}